<?php

namespace ForumBundle\Controller;

use ForumBundle\Entity\CommentaireForum;
use ForumBundle\Entity\Forum;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

/**
 * Forum controller.
 *
 */
class ForumController extends Controller
{
    /**
     * Lists all forum entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $forums = $em->getRepository('ForumBundle:Forum')->findAll();

        return $this->render('forum/showadmin.html.twig', array(
            'forums' => $forums,
        ));
    }

    /**
     * Creates a new forum entity.
     *
     */
    public function newAction(Request $request)
    {
        $forum = new Forum();
        $form = $this->createForm('ForumBundle\Form\ForumType', $forum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var UploadedFile $file
             */
            $file=$forum->getImage();
            $filename = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move($this->getParameter('images_directory'),$filename);
            $forum->setImage($filename);
            $forum->setUser($this->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($forum);
            $em->flush();

            return $this->redirectToRoute('forum_show', array('id' => $forum->getId()));
        }

        return $this->render('forum/new.html.twig', array(
            'forum' => $forum,
            'form' => $form->createView(),
        ));
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    /**
     * Finds and displays a forum entity.
     *
     */
    public function showAction(Forum $forum)
    {

        $commentaireForum = new CommentaireForum();
        $em = $this->getDoctrine()->getManager();
        $deleteForm = $this->createDeleteForm($forum);
        $commentaireForums = $em->getRepository('ForumBundle:CommentaireForum')->findByForum($forum->getId());
        return $this->render('forum/show.html.twig', array(
            'forum' => $forum,
            'delete_form' => $deleteForm->createView(),
            'commentaireForums' => $commentaireForums,
            'form'=> $form = $this->createForm('ForumBundle\Form\CommentaireForumType', $commentaireForum)->createView(),

        ));
    }

    /**
     * Displays a form to edit an existing forum entity.
     *
     */
    public function editAction(Request $request, Forum $forum)
    {
        $deleteForm = $this->createDeleteForm($forum);
        $editForm = $this->createForm('ForumBundle\Form\ForumType', $forum);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('forum_edit', array('id' => $forum->getId()));
        }

        return $this->render('forum/edit.html.twig', array(
            'forum' => $forum,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a forum entity.
     *
     */
    public function deleteAction(Request $request, Forum $forum)
    {
        $form = $this->createDeleteForm($forum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($forum);
            $em->flush();
        }

        return $this->redirectToRoute('forum_index');
    }

    /**
     * Creates a form to delete a forum entity.
     *
     * @param Forum $forum The forum entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Forum $forum)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('forum_delete', array('id' => $forum->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}
