<?php

namespace EventBundle\Repository;

/**
 * EventBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
