<?php

namespace ForumBundle\Repository;

/**
 * CommentForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentForumRepository extends \Doctrine\ORM\EntityRepository
{
}
