<?php

namespace ForumBundle\Repository;

/**
 * CommenatireForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommenatireForumRepository extends \Doctrine\ORM\EntityRepository
{
}
