<?php

namespace ForumBundle\Repository;

/**
 * helloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class helloRepository extends \Doctrine\ORM\EntityRepository
{
}
